module.exports = {
	APP_INFO: 'get-appInfo',
	LOGIN: 'login',
	BACKUP: 'backup',
	QUIT: 'quit-app',
	TEST_PRINT: 'test-print',
	PRINT: 'print',
	FIND_MEMBERSHIP: 'find:membership',
	ADD_MEMBERSHIP: 'add:membership',
	EDIT_MEMBERSHIP: 'edit:membership',
	DELETE_MEMBERSHIP: 'delete:membership',
	RENEW_MEMBERSHIP: 'renew:membership',
	BUY_MEMBERSHIP: 'buy:membership',
	CHECK_DUPLICATE_ACCOUNT: 'duplicate:membership',
	LATEST_MEMBERSHIP_RECORD: 'latest:membership:record',
	DELETE_RECORD: 'delete:record',
	MEMBERSHIP_HISTORY: 'membership:history',
	PRINT_RECEIPT: 'print:receipt',
	PRINT_REPORT: 'print:report',
};
